name: Build PR
on: pull_request
jobs:
  gradle:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: gradle/wrapper-validation-action@v1
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
